name: '${name}'
version: '${version}'
main: '${group}.${name.toLowerCase()}.${name}'
api-version: '${MinecraftVersion}'
author: Blugon
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${KotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${KotlinVersion}

commands:
  sethome:
    description: "Set Home"
  delhome:
    description: "Delete home"
  home:
    description: "Teleport to home"